"""Default crawl seeds — popular direct deps, walk downward."""

from __future__ import annotations

SEED_PACKAGES: tuple[str, ...] = (
    # Server frameworks and HTTP
    "express",
    "koa",
    "fastify",
    "@nestjs/core",
    "axios",
    "node-fetch",
    "got",
    "superagent",
    # Front end
    "react",
    "react-dom",
    "vue",
    "svelte",
    "next",
    "@angular/core",
    "redux",
    "@reduxjs/toolkit",
    "react-router",
    # Build and bundling
    "webpack",
    "vite",
    "rollup",
    "esbuild",
    "parcel",
    "@babel/core",
    "typescript",
    "ts-node",
    "tsup",
    # Testing
    "jest",
    "mocha",
    "vitest",
    "cypress",
    "playwright",
    "@testing-library/react",
    "sinon",
    "chai",
    "supertest",
    # Linting and formatting
    "eslint",
    "prettier",
    "@typescript-eslint/parser",
    "stylelint",
    "husky",
    "lint-staged",
    # Data and persistence
    "mongoose",
    "sequelize",
    "prisma",
    "typeorm",
    "knex",
    "pg",
    "mysql2",
    "redis",
    "ioredis",
    # Utilities that end up everywhere
    "lodash",
    "underscore",
    "ramda",
    "moment",
    "dayjs",
    "date-fns",
    "uuid",
    "nanoid",
    "chalk",
    "commander",
    "yargs",
    "debug",
    "dotenv",
    "semver",
    "glob",
    "rimraf",
    "cross-env",
    "minimist",
    # Validation and serialisation
    "zod",
    "joi",
    "yup",
    "ajv",
    "class-validator",
    # Auth, crypto, security
    "jsonwebtoken",
    "bcrypt",
    "passport",
    "helmet",
    "cors",
    # Observability and infrastructure
    "winston",
    "pino",
    "morgan",
    "@sentry/node",
    "prom-client",
    "socket.io",
    "graphql",
    "apollo-server",
    "bull",
    "node-cron",
    # Tooling frequently present in CI
    "nodemon",
    "concurrently",
    "npm-run-all",
    "sharp",
    "puppeteer",
)


def default_seeds() -> list[str]:
    return list(SEED_PACKAGES)
